# Generated by Django 3.1.4 on 2022-05-03 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('dieuthinsi', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('eksamino', models.IntegerField()),
                ('A_M', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Blospost',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=2000)),
                ('tag', models.CharField(max_length=100)),
                ('date_posted', models.DateField(max_length=100)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
